### ISSUE TITLE
ImportError: cannot import name 'EnsemblRequest'

### ISSUE THREAD

**Issue by samskim** [jeremymcrae/denovonear#3]
Hi,

i installed both denovonear and fitDNM, and it looks like "EnsemblRequest" is not getting imported (called by mutation_rates.py). I checked "from denovonear.ensembl_requester import EnsemblRequest", and ensembl_requester does not seem to include EnsemblRequest. Can you point to me where EnsemblRequest is defined?

**Comment by jeremymcrae** [comment]
sorry, I had changed how denovonear operated, and hadn't updated fitDNM to match. I've updated fitDNM now. Although, I should note that I just threw my fitDNM repository together for testing modifications to fitDNM, but then ultimately decided not to use fitDNM for de novo enrichment testing.

Also, I only checked that the fitDNM unit tests ran without error, I didn't make any further checks to fitDNMs operation.
